INSERT INTO tpdosdesi.ciudad (nombre, pais)
VALUES 
('Tokio', 'Japón'),
('Delhi', 'India'),
('Shanghai', 'China'),
('São Paulo', 'Brasil'),
('Mumbai', 'India'),
('Ciudad de México', 'México'),
('Beijing', 'China'),
('El Cairo', 'Egipto'),
('Dhaka', 'Bangladesh'),
('Osaka', 'Japón'),
('Karachi', 'Pakistán'),
('Chongqing', 'China'),
('Estambul', 'Turquía'),
('Buenos Aires', 'Argentina'),
('Kolkata', 'India'),
('Lagos', 'Nigeria'),
('Kinshasa', 'República Democrática del Congo'),
('Manila', 'Filipinas'),
('Río de Janeiro', 'Brasil'),
('Guangzhou', 'China'),
('Lima', 'Perú'),
('Bangkok', 'Tailandia'),
('Shenzhen', 'China'),
('Nueva York', 'Estados Unidos'),
('Bengala', 'India'),
('Teherán', 'Irán'),
('Londres', 'Reino Unido'),
('Chennai', 'India'),
('Lisboa', 'Portugal'),
('Bogotá', 'Colombia'),
('Hong Kong', 'China'),
('Tianjin', 'China'),
('Lahore', 'Pakistán'),
('Bangalore', 'India'),
('Chongjin', 'Corea del Norte'),
('Hyderabad', 'India'),
('Ahmedabad', 'India'),
('Ho Chi Minh', 'Vietnam'),
('Bagdad', 'Irak'),
('Riad', 'Arabia Saudita'),
('Santiago', 'Chile'),
('Singapur', 'Singapur'),
('Sídney', 'Australia'),
('Casablanca', 'Marruecos'),
('Montreal', 'Canadá'),
('Yakarta', 'Indonesia'),
('Durban', 'Sudáfrica'),
('San Petersburgo', 'Rusia'),
('Nairobi', 'Kenia'),
('Dallas', 'Estados Unidos'),
('Phoenix', 'Estados Unidos'),
('Toronto', 'Canadá'),
('Houston', 'Estados Unidos'),
('Belo Horizonte', 'Brasil'),
('Johannesburgo', 'Sudáfrica'),
('Casablanca', 'Marruecos'),
('Abiyán', 'Costa de Marfil'),
('Kinsasa', 'República Democrática del Congo'),
('San Diego', 'Estados Unidos'),
('Miami', 'Estados Unidos'),
('Denver', 'Estados Unidos'),
('Las Vegas', 'Estados Unidos'),
('Atlanta', 'Estados Unidos'),
('Seattle', 'Estados Unidos'),
('Vancouver', 'Canadá'),
('Montreal', 'Canadá'),
('Nueva Orleans', 'Estados Unidos'),
('Santo Domingo', 'República Dominicana'),
('Caracas', 'Venezuela'),
('La Habana', 'Cuba'),
('Bridgetown', 'Barbados'),
('Ciudad de Guatemala', 'Guatemala'),
('Ciudad de Panamá', 'Panamá'),
('San Juan', 'Puerto Rico'),
('San José', 'Costa Rica'),
('Tegucigalpa', 'Honduras'),
('San Salvador', 'El Salvador'),
('Managua', 'Nicaragua'),
('Puerto Príncipe', 'Haití'),
('Buenos Aires', 'Argentina'),
('Santiago', 'Chile'),
('La Paz', 'Bolivia'),
('Lima', 'Perú'),
('Quito', 'Ecuador'),
('Asunción', 'Paraguay'),
('Brasilia', 'Brasil'),
('Bogotá', 'Colombia'),
('Caracas', 'Venezuela'),
('Georgetown', 'Guyana'),
('Paramaribo', 'Surinam'),
('Cayena', 'Guayana Francesa');